// src/components/Reports.vue
<template>
  <div class="reports-container">
    <ul>
      <li
        v-for="report in reports"
        :key="report.rule + report.startLine + report.startColumn"
        :style="{ color: report.severity === 2 ? '#e73232' : '#e6ac00' }"
        @click="locate({ line: report.startLine, column: report.startColumn })"
      >
        <span class="tiny-spacing">
          <icon-error v-if="report.severity === 2" />
          <icon-warning v-else />
        </span>
        <span class="tiny-spacing">{{ report.message }}</span>
        <span v-if="report.rule" class="tiny-spacing">
          ({{ report.rule }})
        </span>
        <span>({{ report.startLine }}, {{ report.startColumn }})</span>
      </li>
    </ul>
  </div>
</template>

<script>
import IconError from './icons/Error.vue'
import IconWarning from './icons/Warning.vue'
import * as emitter from '../events'

export default {
  name: 'Reports',
  components: {
    IconError,
    IconWarning
  },
  props: ['reports'],
  methods: {
    locate(position) {
      emitter.emit('editor-locate', position)
    }
  }
}
</script>

<style lang="stylus">
.reports-container
  max-height calc(100vh - 70vh - 34px)

  ul
    margin 0
    padding-left 0
    max-height calc(100vh - 70vh - 34px)
    overflow-x hidden
    overflow-y scroll

    li
      list-style none
      padding 5px 0 5px 10px
      margin 0
      border-bottom 1px solid #ccc

      &:hover
        cursor pointer
        background-image linear-gradient(
          to bottom,
          rgba(0, 0, 0, 0.065),
          rgba(0, 0, 0, 0.0325) 67%,
          rgba(0, 0, 0, 0.065)
        )

.tiny-spacing
  padding-right 4px
</style>

// src/components/Reports.tsx
import { h, Component } from 'preact'
import styled, { css } from 'preact-emotion'
import { observer, inject } from 'mobx-preact'
import { Store } from '../store'
import { Subject } from 'rxjs'
import IconError from './icons/Error'
import IconWarning from './icons/Warning'

export const positioning: Subject<[number, number]> = new Subject()

const tinySpacing = css`
  padding-right: 4px;
`

const Container = styled('div')`
  max-height: calc(100vh - 70vh - 34px);
`

const List = styled('ul')`
  margin: 0;
  padding-left: 0;
  max-height: calc(100vh - 70vh - 34px);
  overflow-x: hidden;
  overflow-y: scroll;
`

// @ts-ignore
const ListItem = styled('li')`
  list-style: none;
  padding: 5px 0 5px 10px;
  margin: 0;
  border-bottom: 1px solid #ccc;
  color: ${props => props.severity === 2 ? '#e73232' : '#e6ac00'};

  &:hover {
    cursor: pointer;
    background-image: linear-gradient(
      to bottom,
      rgba(0,0,0,0.065),
      rgba(0,0,0,0.0325) 67%,
      rgba(0,0,0,0.065)
    );
  }
`

@inject('store')
@observer
export default class extends Component<{ store: Store }> {
  render ({ store }: { store: Store }) {
    return (
      <Container>
        <List>
        {store.linterReports.map(report => (
          <ListItem
            severity={report.severity}
            onClick={() => positioning.next([report.line, report.column])}
          >
            <span class={tinySpacing}>
              {report.severity === 2 ? <IconError /> : <IconWarning />}
            </span>
            <span class={tinySpacing}>{report.message}</span>
            {
              report.ruleId
                ? <span class={tinySpacing}>({report.ruleId})</span>
                : null
            }
            ({report.line}, {report.column})
          </ListItem>
        ))}
        </List>
      </Container>
    )
  }
}
