// src/components/sidebar/ParserOptions.vue
<template>
  <ConfigurationItem title="Parser Options">
    <li>
      <div>
        Parser:
        <select
          :disabled="$store.state.eslint.parser !== 'vue-eslint-parser'"
          @change="changeParser"
        >
          <option v-for="parser in parsers" :key="parser" :value="parser">
            {{ parser }}
          </option>
        </select>
        <div>(Only available when using "vue-eslint-parser")</div>
      </div>
    </li>
  </ConfigurationItem>
</template>

<script>
import ConfigurationItem from './ConfigurationItem.vue'
import * as emitter from '../../events'

export default {
  name: 'ParserOptions',
  components: {
    ConfigurationItem
  },
  data() {
    return {
      parsers: ['espree', 'babel-eslint', 'typescript-eslint-parser']
    }
  },
  methods: {
    changeParser({ target: { value } }) {
      this.$store.commit('updateParserOptions', { parser: value })
      emitter.emit('lint')
    }
  }
}
</script>

<style lang="stylus" scoped>
select
  margin-left 5px
</style>

// src/components/sidebar/ParserOptions.tsx
import { h, Component } from 'preact'
import { observer } from 'mobx-preact'
import { Linter } from 'eslint'
import { ConfigurationItem } from './ConfigurationItem'

const parsers = [
  'espree',
  'babel-eslint',
  'typescript-eslint-parser'
]

interface Props {
  currentParser: string
  updateParserOptions(options: Linter.ParserOptions): void
}

interface State {
  opened: boolean
}

@observer
export default class extends Component<Props, State> {
  state = {
    opened: false
  }

  constructor(props) {
    super(props)
    this.onTitleClick = this.onTitleClick.bind(this)
    this.changeParser = this.changeParser.bind(this)
  }

  onTitleClick() {
    this.setState(prevState => ({ opened: !prevState.opened }))
  }

  changeParser({ target }: Event) {
    const { value } = target as HTMLSelectElement
    this.props.updateParserOptions({ parser: value })
  }

  render(props: Props, { opened }: State) {
    if (opened) {
      return (
        <ConfigurationItem title="Parser Options" onClick={this.onTitleClick}>
          <div>
            Parser:
            <select
              disabled={props.currentParser !== 'vue-eslint-parser'}
              onChange={this.changeParser}
              style={{ marginLeft: '5px' }}
            >
              {parsers.map(parser => (
                <option value={parser}>{parser}</option>
              ))}
            </select>
            <br />
            (Only available when using "vue-eslint-parser")
          </div>
        </ConfigurationItem>
      )
    } else {
      return (
        <ConfigurationItem
          title="Parser Options"
          onClick={this.onTitleClick}
        />
      )
    }
  }
}
